Repository codeit-moving/moving-fe, pull requests merged in 2024-12, with the labels that each got.

#9 [임송이] Card 세부 컴포넌트
  .storybook/preview.ts
  package-lock.json
  package.json
  public/assets/icons/ic_like_active.svg
  public/assets/icons/ic_like_inactive.svg
  public/assets/icons/ic_star_inactive.svg
  public/assets/images/img_avatar_red.svg
  src/app/fonts/pretendard.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/LineSeparator.tsx
  src/components/common/card/FavoriteUi.stories.tsx
  src/components/common/card/FavoriteUi.tsx
  src/components/common/card/MoverInfo.tsx
  src/components/common/card/ProfileImage.stories.tsx
  src/components/common/card/ProfileImage.tsx
  src/components/common/card/ServiceChip.stories.tsx
  src/components/common/card/ServiceChip.tsx
  src/utils/utilFunctions.ts
  src/variables/images.js
  tailwind.config.ts
Labels: 진행 중 🌀

#11 [임송이] 카드 세부 컴포넌트 추가 및 카드 컴포넌트
  src/components/cards/MoverInfoCard.stories.tsx
  src/components/cards/MoverInfoCard.tsx
  src/components/cards/PendingRequestCard.stories.tsx
  src/components/cards/PendingRequestCard.tsx
  src/components/common/LineSeparator.tsx
  src/components/common/card/CardContainer.tsx
  src/components/common/card/GrayLabel.stories.tsx
  src/components/common/card/GrayLabel.tsx
  src/components/common/card/MoverInfo.stories.tsx
  src/components/common/card/MoverInfo.tsx
  src/components/common/card/ProfileImage.tsx
  src/components/common/card/ServiceChip.stories.tsx
  src/components/common/card/ServiceChip.tsx
  src/types/mover.d.ts
  src/utils/utilFunctions.ts
  src/variables/var.tsx
Labels: 진행 중 🌀

#28 [임송이] 카드 컴포넌트
  src/components/cards/IncomingRequestCard.stories.tsx
  src/components/cards/IncomingRequestCard.tsx
  src/components/cards/MoverProfileCard.tsx
  src/components/cards/PendingRequestCard.stories.tsx
  src/components/cards/PendingRequestCard.tsx
  src/components/cards/SentQuoteCard.stories.tsx
  src/components/cards/SentQuoteCard.tsx
  src/components/common/card/CardContainer.tsx
  src/components/common/card/GrayLabel.stories.tsx
  src/components/common/card/GrayLabel.tsx
  src/components/common/card/NameText.stories.tsx
  src/components/common/card/NameText.tsx
  src/components/common/card/QuoteDetails.stories.tsx
  src/components/common/card/QuoteDetails.tsx
  src/components/common/card/ServiceChip.tsx
  src/components/common/card/TextWithGrayLabel.stories.tsx
  src/components/common/card/TextWithGrayLabel.tsx
  src/types/mover.d.ts
  src/utils/utilFunctions.ts
  src/variables/services.ts
Labels: 진행 중 🌀

#34 [임송이] 카드 컴포넌트
  .github/pull_request_template.md
  src/app/layout.tsx
  src/components/cards/ConfirmedQuoteCard.stories.tsx
  src/components/cards/ConfirmedQuoteCard.tsx
  src/components/cards/MoverProfileCard.tsx
  src/components/cards/PendingRequestCard.stories.tsx
  src/components/cards/ReceivedQuoteCard.stories.tsx
  src/components/cards/ReceivedQuoteCard.tsx
  src/components/cards/RejectedRequestCard.stories.tsx
  src/components/cards/RejectedRequestCard.tsx
  src/components/cards/SentQuoteCard.tsx
  src/components/common/Button.tsx
  src/components/common/LineSeparator.tsx
  src/components/common/card/CardContainer.tsx
  src/components/common/card/MoverExperience.tsx
  src/components/common/card/MoverInfo.tsx
  src/components/common/card/NameText.tsx
  src/components/common/card/ProfileImage.tsx
  src/components/common/card/QuoteDetails.tsx
  src/components/common/card/ServiceChip.tsx
  src/components/common/card/TextWithGrayLabel.tsx
  src/config/cn.ts
Labels: 진행 중 🌀

#35 [임송이] 카드 컴포넌트
  src/components/RatingInfo.tsx
  src/components/cards/CreateReviewCard.stories.tsx
  src/components/cards/CreateReviewCard.tsx
  src/components/cards/FavoriteMoverCard.stories.tsx
  src/components/cards/FavoriteMoverCard.tsx
  src/components/cards/MyReviewCard.stories.tsx
  src/components/cards/MyReviewCard.tsx
  src/components/cards/PendingRequestCard.tsx
  src/components/common/StarRatingDisplay.stories.tsx
  src/components/common/StarRatingDisplay.tsx
  src/components/common/card/GrayLabel.tsx
  src/components/common/card/MoverInfo.tsx
  src/components/common/card/NameText.tsx
  src/components/common/card/ProfileImage.tsx
  src/components/common/card/QuoteDetails.tsx
  src/components/common/card/TextWithGrayLabel.tsx
  src/utils/utilFunctions.ts
Labels: 진행 중 🌀

#44 [임송이] 기사 마이페이지
  package-lock.json
  package.json
  public/assets/icons/ic_ellipsis.svg
  src/api/axios.ts
  src/api/mover.ts
  src/api/mutation-hooks/mover.ts
  src/api/query-hooks/mover.ts
  src/api/queryKeys.ts
  src/app/(mover)/layout.tsx
  src/app/(mover)/mover/my-quote/page.tsx
  src/app/(mover)/mover/mypage/page.tsx
  src/app/(user)/layout.tsx
  src/app/(user)/me/mover/page.tsx
  src/app/layout.tsx
  src/components/Message.tsx
  src/components/cards/FavoriteMoverCard.tsx
  src/components/cards/IncomingRequestCard.tsx
  src/components/common/Loader.stories.tsx
  src/components/common/Loader.tsx
  src/components/common/Pagination.stories.tsx
  src/components/common/Pagination.tsx
  src/components/common/card/CardContainer.tsx
  src/components/layout/Main.tsx
  src/components/layout/QuoteGNBWrapper.tsx
  src/components/review/CustomerReview.tsx
  src/components/review/ReviewImageSlider.tsx
  src/config/queryClient.ts
  src/contexts/queryClientProvider.tsx
  src/variables/images.js
Labels: feature, page

#81 [주영은] auth, customer, mover api 연결
  next.config.ts
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/axios.ts
  src/api/customer.ts
  src/api/mover.ts
  src/api/user.ts
  src/app/(mover)/layout.tsx
  src/app/(mover)/mover/info-edit/page.tsx
  src/app/(mover)/mover/profile-edit/page.tsx
  src/app/(user)/find-mover/[moverId]/page.tsx
  src/app/(user)/layout.tsx
  src/app/(user)/me/info-edit/page.tsx
  src/app/(user)/me/profile-edit/page.tsx
  src/app/layout.tsx
  src/components/auth/LoginComponent.tsx
  src/components/auth/RoleGuard.tsx
  src/components/auth/SignUpComponent.tsx
  src/components/dropdowns/DropdownProfile.tsx
  src/components/forms/InfoEdit.tsx
  src/components/forms/Profile.tsx
  src/components/hooks/useResize.tsx
  src/components/layout/GNB.tsx
  src/components/modals/ConfirmModal.tsx
  src/components/modals/ReviewModal.tsx
  src/middleware.ts
  src/store/signupStore.ts
  src/store/userStore.ts
  src/types/auth.ts
  src/utils/authValidation.ts
Labels: 완료 🎯
